import time

print("▒▒▒▒▒▒▒▒▒▒ 0%\r", end="")
time.sleep(0.5)
print("█▒▒▒▒▒▒▒▒▒ 10%\r", end="")
time.sleep(0.5)
print("██▒▒▒▒▒▒▒▒ 20%\r", end="")
time.sleep(0.5)
print("███▒▒▒▒▒▒▒ 30%\r", end="")
time.sleep(0.5)
print("████▒▒▒▒▒▒ 40%\r", end="")
time.sleep(0.5)
print("█████▒▒▒▒▒ 50%\r", end="")
time.sleep(0.5)
print("██████▒▒▒▒ 60%\r", end="")
time.sleep(0.5)
print("███████▒▒▒ 70%\r", end="")
time.sleep(0.5)
print("████████▒▒ 80%\r", end="")
time.sleep(0.5)
print("█████████▒ 90%\r", end="")
time.sleep(0.5)
print("██████████ 100%\r", end="")
time.sleep(0.5)
